language: python

services:
  - postgresql

python:
  - "3.6"

env:
  - DATABASE_URL="postgres://postgres@localhost:5432/projecttier"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database projecttier;' -d postgres -U postgres

script:
  - coverage run --source='.' manage.py test project_tier

after_success: coveralls
